### PR TITLE
Cleaning

### PR DESCRIPTION
**Pull request by Benny-Nottonson**
Removed unused imports, ran mojo format ., fixed styling for 24.2 and removed inlining (ineffective currently)

### CODE REVIEW

**Comment by StijnWoestenborghs** [comment]
Waw. This made me realise how hard I hate parameter values to be PascalCase

**Comment by Benny-Nottonson** [comment]
> Waw. This made me realise how hard I hate parameter values to be PascalCase. For types/structs it makes sense. But for a value... 

I think it helps development since you know what can be used as a compile time variable, but i'm okay with just Types being PascalCase, your call.

**Comment by StijnWoestenborghs** [comment]
What bothers me is that the std lib is not even following their own styleguide... "Almost" all parameter values are snake cased...

**Comment by StijnWoestenborghs** [comment]
https://discord.com/channels/1087530497313357884/1224427295943688342

**Comment by Benny-Nottonson** [comment]
> What bothers me is that the std lib is not even following their own styleguide... "Almost" all parameter values are snake cased...

Yeah... I mean thats a PR to modular/mojo, might as well get a headstart here

**Pull request closed without merging**
