### PR TITLE
Identify comp overhead & Sin estimate

### PR DESCRIPTION
**Pull request by StijnWoestenborghs**
This PR tries to identify and fix why there is so much overhead when using certain datatypes as compile time constants. And adds a new benchmark, `sin_estimate.mojo` to evaluate the result. 

Example: Removing UUID from Symbol results in an increase in performance.
```
Before:
housing.mojo:  2.8 sec
Time using custom Tensor & references on (AnyPointer) collection:  14.337211644 s
Time using custom Tensor & __get_address_as_lvalue on (AnyPointer) collection:  9.5543818009999999 s

After replacing UUID with a UInt32:
housing.mojo: 0.08 sec
Time using custom Tensor & references on (AnyPointer) collection:  0.243069382 s
Time using custom Tensor & __get_address_as_lvalue on (AnyPointer) collection:  0.16846102700000001 s
```

**BUG**: sin_estimate.mojo seem to be stagnating at a loss of mse 0.06. For 10000 iterations
```
pytorch: 4.15 sec, mse: 1.386e-07
basalt: 12.9 sec, mse: 0.0603
```

### CODE REVIEW

**Comment by StijnWoestenborghs** [comment]
Removing UUID entirely here. The root cause was not uuid on itself being slow in generating. But the String type being wildly inefficient. UUID has been replaced in symbol by a simple counter in the graph of type UInt32. And with uuid being removed there is no need for a StringDict inside the Collection. Reducing overhead and complexity and increased the performance to:
```
housing.mojo: 0.04 sec
Time using custom Tensor & references on (AnyPointer) collection:  0.010930570000000001 s
Time using custom Tensor & __get_address_as_lvalue on (AnyPointer) collection:  0.0095764560000000006 s
```

**Comment by StijnWoestenborghs** [comment]
All changes:
- Removes UUID and StringDict. Symbol.name replaced with a UInt32. Collection changed accordingly.
- Adds a profiler to the main branch (I think I don't want to add this permanently though, but I guess for now it can be there temporarily, as it is pretty convenient)
- Adds a new bench mark: sin_estimate.mojo
- Fixes a bug in vectorization of the ReLU operator.
- Optimizations on the `get_real_index` function used for broadcasting and accumulating gradients.
New performance on the benchmark (double the amount of epochs with previous report):
```
sin_estimate.mojo
pytorch: 7.73 sec, mse: 1.0341e-05
basalt: 1.243 sec, mse: 2.7471e-05
```

**Review by andresnowak — APPROVED** [review]
From what i could see, running the tests, examples and the graph render, everything seems to be okay.

**Comment by StijnWoestenborghs** [comment]
Getting the bugs out but we are starting to see the benefits of the static graph 🚀
Can't wait for matmul/conv

**Pull request merged**
